# Generated by Django 3.1.3 on 2020-11-14 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_period', models.IntegerField(blank=True, default=12)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=30)),
                ('check_smartkeyword', models.BooleanField(blank=True, default=False)),
                ('follower', models.ManyToManyField(related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CrawledData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField(blank=True)),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('image_url', models.URLField(blank=True)),
                ('keywords', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.keyword')),
            ],
        ),
    ]
