# Generated by Django 3.1.3 on 2020-11-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawleddata',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
