# Generated by Django 3.1.3 on 2020-12-02 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20201128_0236'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartKeywordInfo',
            fields=[
                ('sel_keyword', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='common.keyword')),
                ('type', models.TextField(blank=True, default='', null=True)),
                ('url', models.TextField(blank=True, default='', null=True)),
                ('articles', models.TextField(blank=True, default='', null=True)),
                ('target_base', models.TextField(blank=True, default='', null=True)),
                ('title', models.TextField(blank=True, default='', null=True)),
                ('image', models.TextField(blank=True, default='', null=True)),
                ('contents', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
