# Generated by Django 3.1.3 on 2020-12-02 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_smartkeywordinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartkeywordinfo',
            old_name='sel_keyword',
            new_name='keyword',
        ),
    ]
