# Generated by Django 3.1.3 on 2020-12-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20201203_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartkeywordinfo',
            name='type',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
