# Generated by Django 3.1.3 on 2020-12-03 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_remove_keyword_check_smartkeyword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='data_period',
        ),
    ]
