# Generated by Django 3.1.3 on 2020-12-03 06:54

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_remove_profile_data_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alart_time',
            field=multiselectfield.db.fields.MultiSelectField(default=12, max_length=200, verbose_name=((0, '0 oclock'), (1, '1 oclock'), (2, '2 oclock'), (3, '3 oclock'), (4, '4 oclock'), (5, '5 oclock'), (6, '6 oclock'), (7, '7 oclock'), (8, '8 oclock'), (9, '9 oclock'), (10, '10 oclock'), (11, '11 oclock'), (12, '12 oclock'), (13, '13 oclock'), (14, '14 oclock'), (15, '15 oclock'), (16, '16 oclock'), (17, '17 oclock'), (18, '18 oclock'), (19, '19 oclock'), (20, '20 oclock'), (21, '21 oclock'), (22, '22 oclock'), (23, '23 oclock'))),
        ),
    ]
