# Generated by Django 3.1.3 on 2020-12-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_remove_profile_alart_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alart_time',
            field=models.IntegerField(default=16384),
        ),
    ]
