# Generated by Django 3.1.3 on 2020-12-04 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_auto_20201204_0614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='alart_times',
            new_name='alert_times',
        ),
    ]
